/*
 * THIS FILE IS AUTOMATICALLY GENERATED
 *
 * Generator:     sensirion-driver-generator 1.1.2
 * Product:       sfa3x
 * Model-Version: 1.1.0
 */
/*
 * Copyright (c) 2025, Sensirion AG
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 *
 * * Redistributions of source code must retain the above copyright notice, this
 *   list of conditions and the following disclaimer.
 *
 * * Redistributions in binary form must reproduce the above copyright notice,
 *   this list of conditions and the following disclaimer in the documentation
 *   and/or other materials provided with the distribution.
 *
 * * Neither the name of Sensirion AG nor the names of its
 *   contributors may be used to endorse or promote products derived from
 *   this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
 * ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE
 * LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
 * CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
 * SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
 * INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
 * CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
 * ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 */
#include "sensirion_common.h"
#include "sensirion_i2c_hal.h"
#include "sfa3x_i2c.h"
#include <inttypes.h>  // PRIx64
#include <stdio.h>     // printf

#define sensirion_hal_sleep_us sensirion_i2c_hal_sleep_usec

int main(void) {
    int16_t error = NO_ERROR;
    sensirion_i2c_hal_init();
    sfa3x_init(SFA3X_I2C_ADDR_5D);

    error = sfa3x_device_reset();
    if (error != NO_ERROR) {
        printf("error executing device_reset(): %i\n", error);
        return error;
    }
    sensirion_hal_sleep_us(1000000);
    int8_t device_marking[32] = {0};
    error = sfa3x_get_device_marking(device_marking, 32);
    if (error != NO_ERROR) {
        printf("error executing get_device_marking(): %i\n", error);
        return error;
    }
    printf("device_marking: %s\n", device_marking);
    error = sfa3x_start_continuous_measurement();
    if (error != NO_ERROR) {
        printf("error executing start_continuous_measurement(): %i\n", error);
        return error;
    }
    float hcho = 0.0;
    float humidity = 0.0;
    float temperature = 0.0;
    uint16_t repetition = 0;
    for (repetition = 0; repetition < 50; repetition++) {
        sensirion_hal_sleep_us(1000000);
        error = sfa3x_read_measured_values(&hcho, &humidity, &temperature);
        if (error != NO_ERROR) {
            printf("error executing read_measured_values(): %i\n", error);
            continue;
        }
        printf("hcho: %.2f ", hcho);
        printf("humidity: %.2f ", humidity);
        printf("temperature: %.2f\n", temperature);
    }

    error = sfa3x_stop_measurement();
    if (error != NO_ERROR) {
        return error;
    }
    return NO_ERROR;
}
